-- AGROMARBANKA panel v21.1
-- Tabela historii edycji dokumentów / operacji
-- Uruchom w Supabase SQL Editor -> Run

create table if not exists public.historia_edycji_operacji (
  id bigint generated by default as identity primary key,
  operacja_id bigint,
  dokument_id uuid,
  typ_dokumentu text,
  zmienione_przez text,
  zmienione_przez_id text,
  zmieniono_o timestamptz default now(),
  opis_zmiany text,
  przed_zmiana jsonb,
  po_zmianie jsonb
);

create index if not exists idx_historia_edycji_operacji_operacja_id
on public.historia_edycji_operacji(operacja_id);

create index if not exists idx_historia_edycji_operacji_dokument_id
on public.historia_edycji_operacji(dokument_id);

alter table public.historia_edycji_operacji enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies 
    where schemaname='public' 
      and tablename='historia_edycji_operacji' 
      and policyname='historia_edycji_operacji_all'
  ) then
    create policy historia_edycji_operacji_all
    on public.historia_edycji_operacji
    for all
    using (true)
    with check (true);
  end if;
end $$;

-- Test ręczny po uruchomieniu SQL:
-- insert into public.historia_edycji_operacji
-- (operacja_id, typ_dokumentu, zmienione_przez, opis_zmiany, przed_zmiana, po_zmianie)
-- values
-- (1, 'PZ', 'Test', 'Testowa edycja', '{"ilosc":80}', '{"ilosc":60}');
