-- V20.3 - rejestr usuniętych operacji
create table if not exists usuniete_operacje (
  id bigint generated by default as identity primary key,
  operacja_id bigint,
  kontrahent text,
  opakowanie text,
  magazyn text,
  typ text,
  ilosc numeric,
  data_operacji date,
  godzina_operacji text,
  powod text,
  usuniete_przez text,
  usunieto_o timestamp default now()
);

alter table usuniete_operacje add column if not exists operacja_id bigint;
alter table usuniete_operacje add column if not exists kontrahent text;
alter table usuniete_operacje add column if not exists opakowanie text;
alter table usuniete_operacje add column if not exists magazyn text;
alter table usuniete_operacje add column if not exists typ text;
alter table usuniete_operacje add column if not exists ilosc numeric;
alter table usuniete_operacje add column if not exists data_operacji date;
alter table usuniete_operacje add column if not exists godzina_operacji text;
alter table usuniete_operacje add column if not exists powod text;
alter table usuniete_operacje add column if not exists usuniete_przez text;
alter table usuniete_operacje add column if not exists usunieto_o timestamp default now();

alter table usuniete_operacje enable row level security;

drop policy if exists "usuniete_operacje_select_all" on usuniete_operacje;
drop policy if exists "usuniete_operacje_insert_all" on usuniete_operacje;

create policy "usuniete_operacje_select_all"
on usuniete_operacje for select
using (true);

create policy "usuniete_operacje_insert_all"
on usuniete_operacje for insert
with check (true);
