-- AGROMARBANKA panel v23 — historia edycji dokumentów
-- Uruchom w Supabase SQL Editor -> Run

create table if not exists public.historia_edycji_operacji (
  id bigint generated by default as identity primary key,
  dokument_id text,
  zmienione_przez text,
  zmieniono_o timestamptz default now(),
  opis_zmiany text,
  przed_zmiana jsonb,
  po_zmianie jsonb
);

alter table public.historia_edycji_operacji
add column if not exists dokument_id text,
add column if not exists zmienione_przez text,
add column if not exists zmieniono_o timestamptz default now(),
add column if not exists opis_zmiany text,
add column if not exists przed_zmiana jsonb,
add column if not exists po_zmianie jsonb;

create index if not exists idx_historia_edycji_operacji_dokument_id
on public.historia_edycji_operacji(dokument_id);

alter table public.historia_edycji_operacji enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='historia_edycji_operacji'
      and policyname='historia_edycji_operacji_all'
  ) then
    create policy historia_edycji_operacji_all
    on public.historia_edycji_operacji
    for all
    using (true)
    with check (true);
  end if;
end $$;
