import React, {useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import * as XLSX from 'xlsx';
import {Users,Package,Warehouse,FileDown,Trash2,Eye,EyeOff,Printer,LogOut} from 'lucide-react';
import './style.css';

const DEFAULT_SUPABASE_URL='https://wvdihlztlgwpmqoaobxc.supabase.co';
const url=import.meta.env.VITE_SUPABASE_URL || localStorage.getItem('VITE_SUPABASE_URL') || DEFAULT_SUPABASE_URL;
const key=import.meta.env.VITE_SUPABASE_ANON_KEY || localStorage.getItem('VITE_SUPABASE_ANON_KEY') || '';
const supabase = url&&key ? createClient(url,key) : null;
const today=()=>new Date().toISOString().slice(0,10);
const norm=(s='')=>s.toString().toLowerCase().trim();

function App(){
 const [ready,setReady]=useState(false),[err,setErr]=useState(''),[me,setMe]=useState(null),[tab,setTab]=useState('operacje');
 const [kontrahenci,setKontrahenci]=useState([]),[opakowania,setOpakowania]=useState([]),[magazyny,setMagazyny]=useState([]),[users,setUsers]=useState([]),[operacje,setOperacje]=useState([]),[usuniete,setUsuniete]=useState([]);
 const load=async()=>{ if(!supabase){setErr('Brak zmiennych VITE_SUPABASE_URL lub VITE_SUPABASE_ANON_KEY w Vercel.'); setReady(true); return}
  try{
   const tables=['kontrahenci','opakowania','magazyny','uzytkownicy','operacje','usuniete_operacje'];
   const [k,o,m,u,op,del]=await Promise.all(tables.map(t=>supabase.from(t).select('*').order('id',{ascending:true})));
   for(const r of [k,o,m,u,op,del]) if(r.error) throw r.error;
   setKontrahenci(k.data||[]); setOpakowania(o.data||[]); setMagazyny(m.data||[]); setUsers(u.data||[]); setOperacje(op.data||[]); setUsuniete(del.data||[]); setReady(true);
  }catch(e){setErr('Błąd połączenia z Supabase: '+(e.message||e)); setReady(true)}
 };
 useEffect(()=>{load()},[]);
 if(!ready) return <Shell><div className="login"><h2>Ładowanie systemu...</h2></div></Shell>;
 if(err) return <SetupSupabase/>;
 if(!me) return <Login users={users} setMe={setMe}/>;
 const ctx={me,load,kontrahenci,opakowania,magazyny,users,operacje,usuniete,setTab};
 return <Shell>
   <header className="top"><div><b>Agromarbanka</b><span>Online Supabase</span></div><button onClick={()=>setMe(null)}><LogOut size={16}/> Wyloguj</button></header>
   <nav>{['operacje','kontrahenci','opakowania','magazyny','raporty','uzytkownicy','usuniete'].filter(x=>me.rola==='admin'||!['uzytkownicy','usuniete'].includes(x)).map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{label(x)}</button>)}</nav>
   {tab==='operacje'&&<Operacje {...ctx}/>} {tab==='kontrahenci'&&<Kontrahenci {...ctx}/>} {tab==='opakowania'&&<Opakowania {...ctx}/>} {tab==='magazyny'&&<Magazyny {...ctx}/>} {tab==='raporty'&&<Raporty {...ctx}/>} {tab==='uzytkownicy'&&<Uzytkownicy {...ctx}/>} {tab==='usuniete'&&<Usuniete {...ctx}/>} 
 </Shell>
}

function SetupSupabase(){
 const [u,setU]=useState(localStorage.getItem('VITE_SUPABASE_URL')||DEFAULT_SUPABASE_URL);
 const [k,setK]=useState(localStorage.getItem('VITE_SUPABASE_ANON_KEY')||'');
 const save=()=>{ if(!u||!k) return alert('Wklej URL i klucz Supabase'); localStorage.setItem('VITE_SUPABASE_URL',u.trim()); localStorage.setItem('VITE_SUPABASE_ANON_KEY',k.trim()); location.reload(); };
 return <Shell><div className="login"><h2>Konfiguracja Supabase</h2><p className="info">Nie trzeba już ustawiać zmiennych w Vercel. Wklej klucz raz tutaj.</p><label>Supabase URL</label><input value={u} onChange={e=>setU(e.target.value)}/><label>Anon / publishable key</label><textarea rows="4" value={k} onChange={e=>setK(e.target.value)} placeholder="eyJ... albo sb_publishable_..."/><button className="primary" onClick={save}>Zapisz i uruchom</button><small>Ten klucz jest publiczny dla aplikacji. Nie wklejaj service_role ani secret key.</small></div></Shell>
}

function Shell({children}){return <main><section className="hero"><div><h1>Agromarbanka</h1><p>Nowoczesna obsługa opakowań zwrotnych, magazynu głównego i zapasowego.</p></div></section>{children}</main>}
function label(x){return {operacje:'Operacja',kontrahenci:'Kontrahenci',opakowania:'Opakowania',magazyny:'Magazyny',raporty:'Raporty',uzytkownicy:'Użytkownicy',usuniete:'Usunięte'}[x]}
function Login({users,setMe}){const [tel,setTel]=useState(''),[pin,setPin]=useState(''),[msg,setMsg]=useState(''); const login=()=>{const u=users.find(x=>x.telefon===tel.trim()&&x.pin===pin.trim()&&x.aktywny!==false); if(u) setMe(u); else setMsg('Nieprawidłowy telefon lub PIN')}; return <Shell><div className="login"><h2>Panel logowania</h2><input placeholder="Telefon" value={tel} onChange={e=>setTel(e.target.value)}/><input placeholder="PIN" value={pin} onChange={e=>setPin(e.target.value)} type="password"/><button className="primary" onClick={login}>Zaloguj</button><small>Demo admin: 500000000 / 1111</small>{msg&&<p className="error">{msg}</p>}</div></Shell>}
function SearchSelect({label,items,value,setValue,field='nazwa'}){const [q,setQ]=useState(''); const list=items.filter(x=>!x.ukryty && norm(x[field]).includes(norm(q))).slice(0,50); return <div className="group"><label>{label}</label><input placeholder={'Wyszukaj '+label.toLowerCase()} value={q} onChange={e=>setQ(e.target.value)}/><select value={value} onChange={e=>setValue(e.target.value)}><option value="">Wybierz...</option>{list.map(x=><option key={x.id} value={x[field]}>{x[field]}</option>)}</select></div>}
function Operacje(p){const mags=p.me.rola==='kierowca'&&p.me.magazyn?p.magazyny.filter(m=>m.nazwa===p.me.magazyn):p.magazyny; const [kon,setKon]=useState(''),[opa,setOpa]=useState(''),[mag,setMag]=useState(mags[0]?.nazwa||''),[ilosc,setIlosc]=useState(1),[data,setData]=useState(today()),[podpis,setPodpis]=useState(''); useEffect(()=>{if(!mag&&mags[0])setMag(mags[0].nazwa)},[mags]);
 const save=async(typ)=>{if(!kon||!opa||!mag||!ilosc)return alert('Uzupełnij kontrahenta, opakowanie, magazyn i ilość'); const r=await supabase.from('operacje').insert({kontrahent:kon,opakowanie:opa,magazyn:mag,typ,ilosc:Number(ilosc),data_operacji:data,podpis,uzytkownik:p.me.imie}); if(r.error) return alert(r.error.message); setIlosc(1); setData(today()); setPodpis(''); p.load();};
 return <div className="grid"><section className="card"><h2><Package/> Operacja</h2><SearchSelect label="Kontrahent" items={p.kontrahenci.filter(x=>x.aktywny!==false)} value={kon} setValue={setKon}/><SearchSelect label="Opakowanie" items={p.opakowania.filter(x=>x.aktywne!==false)} value={opa} setValue={setOpa}/><div className="group"><label>Magazyn</label><select value={mag} onChange={e=>setMag(e.target.value)}>{mags.filter(x=>x.aktywny!==false&&!x.ukryty).map(m=><option key={m.id}>{m.nazwa}</option>)}</select></div><div className="row"><div><label>Ilość</label><input type="number" value={ilosc} onChange={e=>setIlosc(e.target.value)}/></div><div><label>Data operacji</label><input type="date" value={data} onChange={e=>setData(e.target.value)}/></div></div><label>Podpis odbiorcy</label><input value={podpis} onChange={e=>setPodpis(e.target.value)} placeholder="Imię i nazwisko"/><div className="row"><button className="big blue" onClick={()=>save('Wydanie')}>Wydanie</button><button className="big green" onClick={()=>save('Zwrot (PZ)')}>Zwrot (PZ)</button></div></section><section className="card"><h2>Ostatnie operacje</h2><Table rows={p.operacje.slice(-8).reverse()} cols={['data_operacji','typ','kontrahent','opakowanie','ilosc','magazyn']}/></section></div>}
function Kontrahenci({kontrahenci,load}){const [n,setN]=useState(''),[g,setG]=useState(''),[lim,setLim]=useState(0),[sal,setSal]=useState(0),[q,setQ]=useState(''); const add=async()=>{if(!n)return; const r=await supabase.from('kontrahenci').insert({nazwa:n,grupa:g,limit_opakowan:Number(lim)||0,saldo_startowe:Number(sal)||0}); if(r.error) alert(r.error.message); setN('');load()}; const upd=async(id,o)=>{await supabase.from('kontrahenci').update(o).eq('id',id);load()}; return <section className="card"><h2><Users/> Kontrahenci</h2><div className="formline"><input placeholder="Nazwa" value={n} onChange={e=>setN(e.target.value)}/><input placeholder="Grupa" value={g} onChange={e=>setG(e.target.value)}/><input placeholder="Limit" type="number" value={lim} onChange={e=>setLim(e.target.value)}/><input placeholder="Saldo startowe" type="number" value={sal} onChange={e=>setSal(e.target.value)}/><button onClick={add}>Dodaj</button></div><input placeholder="Szukaj kontrahenta" value={q} onChange={e=>setQ(e.target.value)}/><List data={kontrahenci.filter(x=>norm(x.nazwa).includes(norm(q)))} render={x=><><b>{x.nazwa}</b><span>{x.grupa||''}</span><Actions x={x} upd={upd}/></>}/></section>}
function Opakowania({opakowania,load}){return <Simple title="Opakowania" icon={<Package/>} table="opakowania" rows={opakowania} name="nazwa" load={load} active="aktywne" hidden="ukryte"/>}
function Magazyny({magazyny,load}){return <Simple title="Magazyny" icon={<Warehouse/>} table="magazyny" rows={magazyny} name="nazwa" load={load} active="aktywny" hidden="ukryty"/>}
function Simple({title,icon,table,rows,name,load,active,hidden}){const [n,setN]=useState(''); const add=async()=>{if(!n)return; await supabase.from(table).insert({[name]:n}); setN('');load()}; const upd=async(id,o)=>{await supabase.from(table).update(o).eq('id',id);load()}; return <section className="card"><h2>{icon} {title}</h2><div className="formline"><input placeholder="Nowa nazwa" value={n} onChange={e=>setN(e.target.value)}/><button onClick={add}>Dodaj</button></div><List data={rows} render={x=><><b>{x[name]}</b><span>{x[active]===false?'Nieaktywny':'Aktywny'} {x[hidden]?'· Ukryty':''}</span><button onClick={()=>upd(x.id,{[active]:!x[active]})}>{x[active]===false?'Aktywuj':'Dezaktywuj'}</button><button onClick={()=>upd(x.id,{[hidden]:!x[hidden]})}>{x[hidden]?'Pokaż':'Ukryj'}</button></>}/></section>}
function Uzytkownicy({users,magazyny,load}){const [u,setU]=useState({imie:'',telefon:'',pin:'',rola:'kierowca',magazyn:''}); const add=async()=>{if(!u.imie||!u.telefon||!u.pin)return; const r=await supabase.from('uzytkownicy').insert(u); if(r.error) alert(r.error.message); setU({imie:'',telefon:'',pin:'',rola:'kierowca',magazyn:''}); load()}; const upd=async(id,o)=>{await supabase.from('uzytkownicy').update(o).eq('id',id);load()}; return <section className="card"><h2>Użytkownicy</h2><div className="formline"><input placeholder="Imię" value={u.imie} onChange={e=>setU({...u,imie:e.target.value})}/><input placeholder="Telefon" value={u.telefon} onChange={e=>setU({...u,telefon:e.target.value})}/><input placeholder="PIN" value={u.pin} onChange={e=>setU({...u,pin:e.target.value})}/><select value={u.rola} onChange={e=>setU({...u,rola:e.target.value})}><option>admin</option><option>magazynier</option><option>kierowca</option></select><select value={u.magazyn||''} onChange={e=>setU({...u,magazyn:e.target.value})}><option value="">Bez przypisania</option>{magazyny.map(m=><option key={m.id}>{m.nazwa}</option>)}</select><button onClick={add}>Dodaj</button></div><List data={users.filter(x=>!x.ukryty)} render={x=><><b>{x.imie}</b><span>{x.telefon} · {x.rola} · {x.magazyn||'wszystkie'}</span><button onClick={()=>upd(x.id,{aktywny:!x.aktywny})}>{x.aktywny?'Dezaktywuj':'Aktywuj'}</button><button onClick={()=>upd(x.id,{ukryty:!x.ukryty})}>{x.ukryty?'Pokaż':'Ukryj'}</button></>}/></section>}
function Actions({x,upd}){return <><button onClick={()=>upd(x.id,{aktywny:!x.aktywny})}>{x.aktywny===false?'Aktywuj':'Dezaktywuj'}</button><button onClick={()=>upd(x.id,{ukryty:!x.ukryty})}>{x.ukryty?'Pokaż':'Ukryj'}</button></>}
function Raporty({operacje,kontrahenci}){const [od,setOd]=useState(''),[doo,setDoo]=useState(today()),[kon,setKon]=useState(''); const rows=operacje.filter(o=>(!od||o.data_operacji>=od)&&(!doo||o.data_operacji<=doo)&&(!kon||o.kontrahent===kon)); const sum=rows.reduce((a,o)=>{const k=o.opakowanie; a[k]=(a[k]||0)+(o.typ.includes('Zwrot')?-Number(o.ilosc):Number(o.ilosc)); return a},{}); const exportX=()=>{const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Operacje'); XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(Object.entries(sum).map(([opakowanie,saldo])=>({opakowanie,saldo}))),'Podsumowanie'); XLSX.writeFile(wb,'raport_agromarbanka.xlsx')}; return <section className="card"><h2><FileDown/> Raporty</h2><div className="formline"><input type="date" value={od} onChange={e=>setOd(e.target.value)}/><input type="date" value={doo} onChange={e=>setDoo(e.target.value)}/><select value={kon} onChange={e=>setKon(e.target.value)}><option value="">Wszyscy kontrahenci</option>{kontrahenci.map(k=><option key={k.id}>{k.nazwa}</option>)}</select><button onClick={exportX}>Pobierz Excel</button><button onClick={()=>window.print()}><Printer size={14}/> Drukuj</button></div><h3>Podsumowanie</h3><Table rows={Object.entries(sum).map(([opakowanie,saldo])=>({opakowanie,saldo}))} cols={['opakowanie','saldo']}/><h3>Historia</h3><Table rows={rows} cols={['data_operacji','typ','kontrahent','opakowanie','ilosc','magazyn','uzytkownik']}/></section>}
function Usuniete({usuniete}){return <section className="card"><h2><Trash2/> Rejestr usuniętych operacji</h2><Table rows={usuniete} cols={['usunieto_o','kontrahent','opakowanie','typ','ilosc','usuniete_przez','powod']}/></section>}
function Table({rows,cols}){return <div className="table"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{cols.map(c=><td key={c}>{r[c]}</td>)}</tr>)}</tbody></table></div>}
function List({data,render}){return <div>{data.map(x=><div className="item" key={x.id}>{render(x)}</div>)}</div>}

createRoot(document.getElementById('root')).render(<App/>);
